base:
  bind: 0.0.0.0
  port: 6379
  maxClients: 1
  pidFile:
  logFile:
  logLevel: debug
  dbFileName: gedis.db
  dbFileDIr: ~/.redis
  maxMemory: 4096
masterSlaveMode:
  slaveOf:
  masterAuth:
  slaveReadOnly: true
appendMode:
  appendOnly: true
  appendFileName:
  appendFsync: